version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 123456a@
      DB_NAME: url_shortener
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 123456a@
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
